version: '3'
services:
  postgres:
    image: postgres:11.6
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
      POSTGRES_DB: qadb
  #  pip install --upgrade pip &&
  #  pip install farm-haystack[ocr,all-gpu]==1.4.0 &&
  # after checking 
  # # && apt autoremove -y &
  # pip install --upgrade pip &&
                  # pip install --upgrade pip &&
  web:
    restart: always
    environment:
      - DJANGO_SECRET_KEY=rthrtht63=2g*8^6o-u(0w#=x0g1_ejoer))29gzm@18#t@whfdsefefserhgserh
    build: ./
    command: >
      bash -c " pip install --upgrade pip &&
                pip install bootstrap4 Pillow

                python wait_for_postgres.py &&
                ./manage.py makemigrations &&
               ./manage.py migrate &&
               ./manage.py runserver 0.0.0.0:8000
              "
  
    volumes:
      - ./:/code
    ports:
      - '8000:8000'
    depends_on:
      - postgres