# Generated by Django 3.2.5 on 2023-11-02 00:13

from django.db import migrations, models
import django.db.models.deletion
import job.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('job_type', models.CharField(choices=[('Full Time', 'Full time'), ('Part Time', 'Part Time')], max_length=50)),
                ('descriptions', models.TextField(max_length=1000)),
                ('published_add', models.DateTimeField(auto_now=True)),
                ('vacancy', models.IntegerField(default=1)),
                ('salary', models.IntegerField(default=0)),
                ('experiences', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to=job.models.upload_image)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('catagorys', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.categorys')),
            ],
        ),
        migrations.CreateModel(
            name='User_apply_job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('website', models.URLField()),
                ('coverletter', models.TextField(max_length=3000)),
                ('create_at', models.DateField(auto_now=True)),
                ('apply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appl_job', to='job.job')),
            ],
        ),
    ]
