# Generated by Django 4.2.5 on 2023-10-07 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('job_type', models.CharField(choices=[('Full Time', 'Full time'), ('Part Time', 'Part Time')], max_length=50)),
                ('descriptions', models.TextField(max_length=1000)),
                ('published_add', models.DateTimeField(auto_now=True)),
                ('vacancy', models.IntegerField(default=1)),
                ('salary', models.IntegerField(default=0)),
                ('experiences', models.IntegerField(default=0)),
                ('catagorys', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.categorys')),
            ],
        ),
    ]
