# Generated by Django 4.2.5 on 2023-10-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.ImageField(default=2, upload_to='jobs/'),
            preserve_default=False,
        ),
    ]
