# Generated by Django 3.2.5 on 2023-10-29 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='catagorys',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='job.categorys'),
            preserve_default=False,
        ),
    ]
