# Generated by Django 3.2.5 on 2023-11-02 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_apply_job',
        ),
    ]
