# Generated by Django 4.2.5 on 2023-10-13 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='image',
        ),
    ]
