# Generated by Django 3.2.5 on 2023-11-02 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_delete_user_apply_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_apply_job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('website', models.URLField()),
                ('coverletter', models.TextField(max_length=3000)),
                ('create_at', models.DateField(auto_now=True)),
                ('apply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appl_job', to='job.job')),
            ],
        ),
    ]
