# Generated by Django 4.2.5 on 2023-10-16 15:58

from django.db import migrations, models
import job.models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_remove_job_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.ImageField(default='', upload_to=job.models.upload_image),
            preserve_default=False,
        ),
    ]
